name: Build Mac PostgreSQL Extension

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

jobs:
  build-mac:
    name: PostgreSQL 17 Mac
    strategy:
      matrix:
        include:
          - os: macos-latest
            artifact_name: pg_uuidv7-arm-mac-pg17
          - os: macos-13
            artifact_name: pg_uuidv7-intel-mac-pg17
    
    runs-on: ${{ matrix.os }}
    
    steps:
      # Clone repository
      - uses: actions/checkout@v4
      
      # Set up PostgreSQL 17 (macOS)
      - name: Set up PostgreSQL (macOS)
        run: |
          brew install postgresql@17
          echo "$(brew --prefix postgresql@17)/bin" >> $GITHUB_PATH
      
      # Build extension
      - name: Build extension
        run: |
          export PG_CONFIG="$(brew --prefix postgresql@17)/bin/pg_config"
          make
          
      # Upload only the dylib file
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: |
            *.dylib
          compression-level: 9
          retention-days: 5